In [46]:
import pandas as pd 
import numpy as np
import os

base_path = os.path.join(os.getcwd(), 'initial_cleaning', 'final_datasets/')
base_path2 = os.path.join(os.getcwd())

In [47]:
df = pd.read_csv(base_path + '/did_with_all.csv')
df2 = pd.read_csv(base_path + 'merged.csv')
df3 = pd.read_csv(base_path + 'interpoled.csv')
df4 = pd.read_csv(base_path + 'merged_short.csv')
dep = pd.read_csv(base_path + 'depreciation_raw.csv')
ide = pd.read_csv(base_path + 'ide.csv')
ide = ide.sort_values(by=['country', 'year'], ascending=True)
df2 = df2.dropna(axis=1)
df2 = df2.drop(columns=['brevets_pct', 'brevets_tri', 'dem_pct'])

df2['country'].unique()

array(['AUT', 'FIN', 'IRL', 'CHE', 'SWE'], dtype=object)

In [48]:

df2[['NX', 'salary', 'gdp', 'cho', 'ppa', 'public_spending']] = df2[[ 'NX', 'salary', 'gdp', 'cho', 'ppa', 'public_spending']].pct_change()
df2['pop'] = np.log(df2['pop'])
df2['brevets'] = np.log(df2['brevets'])
# ∆∆GDP -> Economic acceleration

In [49]:
df2 = df2[(df2['year'] >= 1996) & (df2['year'] < 2019)]

In [50]:
df2['country'].unique()

array(['AUT', 'FIN', 'IRL', 'CHE', 'SWE'], dtype=object)

In [51]:
df2[df2['country'] == 'CHE'].describe()

,year,brevets,NX,salary,gdp,pop,cho,ppa,public_spending
count,23.00000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000
mean,2007.00000,7.371374,0.073560,0.008040,-3.688897,8.947566,0.026613,-0.020937,0.042721
std,6.78233,0.123304,1.131190,0.014254,17.630964,0.057785,0.136705,0.014743,0.025264
min,1996.00000,7.204149,-2.786105,-0.012220,-84.390049,8.872360,-0.144339,-0.051994,-0.000113
25%,2001.50000,7.282727,-0.074714,-0.003164,-0.504375,8.897612,-0.081455,-0.030897,0.026043
50%,2007.00000,7.355641,0.043912,0.005458,-0.283015,8.936145,0.016642,-0.018452,0.040413
75%,2012.50000,7.439841,0.350255,0.015237,0.325560,8.992554,0.088626,-0.010056,0.058422
max,2018.00000,7.651596,3.902865,0.055586,3.798262,9.049506,0.408003,0.003155,0.095431

In [52]:
print(ide.head(1))
print(dep.head(1))

     year country       IDE
179  1988     AUT  0.334055
    id  year  depreciation  ratio_dbrut
0  AUT  1995      43739.34     0.447902

In [53]:
ide['IDE'] = ide['IDE'].pct_change()    
ide = ide[(ide['year'] >= 1996) & (ide['year'] < 2019)]
dep['depreciation'] = dep['depreciation'].pct_change()
dep['ratio_dbrut'] = dep['ratio_dbrut'].pct_change()
dep = dep[(dep['year'] >= 1996) & (dep['year'] < 2019)]

In [54]:
dep.rename(columns={'id': 'country'}, inplace=True)

In [55]:
df2 = pd.merge(df2, ide, on=['country', 'year'], how='left')

In [56]:
# For patents
df2['country'].unique()
df2.to_csv('/Users/jey/Desktop/Datascience/final_files/final_clean/patents_dataset.csv', index=False)

In [57]:
dep.country.unique()

array(['AUT', 'FIN', 'IRL'], dtype=object)

In [58]:
df2 = df2[(df2['country'] != 'SWE') & (df2['country'] != 'CHE')] ## Missing Values for SWE / CHE
df2.country.unique()

array(['AUT', 'FIN', 'IRL'], dtype=object)

In [59]:
df2 = pd.merge(df2, dep, on=['country', 'year'], how='left')
df2.head()

,country,year,brevets,NX,salary,gdp,pop,cho,ppa,public_spending,IDE,depreciation,ratio_dbrut
0,AUT,1996,9.610726,0.201729,-0.006855,-0.169498,8.982061,0.215484,-0.004415,0.041468,1.406747,0.056838,0.002113
1,AUT,1997,9.652395,-0.428677,-0.008273,-0.031561,8.983194,-0.025326,-0.002641,0.016204,-0.311722,0.056120,-0.003015
2,AUT,1998,9.730146,-0.104218,0.031968,0.627749,8.984291,0.065154,-0.009559,0.041098,0.670037,0.065051,-0.008570
3,AUT,1999,9.965429,-0.005612,0.022200,0.077027,8.986237,-0.143091,0.001231,0.048799,-0.346392,0.076619,-0.005696
4,AUT,2000,10.214788,-0.124520,0.003100,-0.152157,8.988642,-0.002762,-0.017752,0.052545,2.147245,0.089553,-0.000423

In [60]:
# For Depreciation
# df2.to_csv('/Users/jey/Desktop/Datascience/final_files/final_clean/depreciation_dataset.csv', index=False)

In [61]:
df = pd.read_csv(os.path.join(base_path2, 'final_clean', 'depreciation_dataset.csv'))
zf = pd.read_csv(os.path.join(base_path2, 'final_clean', 'patents_dataset.csv'))

In [62]:
zf.columns

Index(['country', 'year', 'brevets', 'NX', 'salary', 'gdp', 'pop', 'cho',
       'ppa', 'public_spending', 'IDE'],
      dtype='object')

In [63]:
df.country.unique()

array(['AUT', 'FIN', 'IRL'], dtype=object)

In [64]:
lat_b = zf[(zf['country'] == 'AUT')] # Change here in case to CHE
lat_b = lat_b[['year', 'country', 'brevets', 'gdp', 'pop', 'NX', 'public_spending']]
lat_b = lat_b.describe()
lat_b = lat_b.iloc[1:,1:]
lat_b.loc['skewness'] = lat_b.skew()
lat_b.loc['kurtosis'] = lat_b.kurt()
lat_b.loc['median'] = lat_b.median()
lat_b = lat_b.T
lat_b = lat_b[['mean', 'median', 'std', 'skewness', 'kurtosis', '25%', '75%']]
lat_b

,mean,median,std,skewness,kurtosis,25%,75%
brevets,8.960457,7.487912,1.220555,-1.945070,0.557468,7.487912,10.010883
gdp,-0.359839,-0.031561,1.248854,-1.750552,1.817735,-0.601065,0.281856
pop,9.023869,8.994940,0.032622,-2.645201,0.601198,8.994940,9.042127
NX,-0.743270,-0.124520,2.165271,-2.053429,4.170755,-0.493390,0.207698
public_spending,0.040725,0.041487,0.017502,0.321367,7.258828,0.024916,0.052467

In [65]:
# Save summary, country can be changed in the previouse cell to CHE for CHE summary
lat_b.to_latex('/Users/jey/Desktop/Datascience/final_files/final_LaTeX/summary/brevets_AUT_summary.tex')

In [66]:
df = df[(df['country'] == 'FIN')] # Change here in case for CHE, SWE, FIN, AUT
df = df[['year', 'country', 'depreciation', 'salary', 'cho', 'ppa', 'IDE']]
df = df.describe()
df = df.iloc[1:,1:]
df.loc['skewness'] = df.skew()
df.loc['kurtosis'] = df.kurt()
df.loc['median'] = df.median()
df = df.T
df = df[['mean', 'median', 'std', 'skewness', 'kurtosis', '25%', '75%']]
df

,mean,median,std,skewness,kurtosis,25%,75%
depreciation,0.061280,0.061280,0.049087,-0.168794,2.852770,0.027157,0.103613
salary,0.010804,0.010860,0.010860,0.160362,6.810873,0.003050,0.019853
cho,-0.031283,0.008620,0.098811,1.013048,4.885598,-0.081794,0.008620
ppa,-0.006140,-0.002847,0.013575,-0.322323,7.544923,-0.018134,0.003011
IDE,-0.198059,-0.198059,1.887312,-0.374108,1.323445,-1.478749,0.702093

In [67]:
# Save summary, country name can be changed in the previous
# df.to_latex('/Users/jey/Desktop/Datascience/final_files/final_LaTeX/summary/depreciation_FIN_summary.tex')